project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path_env: "CROWDIN_BASE_PATH"
base_url_env: "CROWDIN_BASE_URL"

preserve_hierarchy: true

files:
	- source: /crowdin/messages.json
	  translation: /translations/%two_letters_code%.json
	  languages_mapping:
		  two_letters_code:
			  zh-CN: zh_cn
			  zh-TW: zh_tw
