
name: Sync translations

on:
    push:
        branches:
            - 'main'

jobs:
    sync_translations:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout to main branch
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install packages
              shell: bash
              run: npm i

            - name: Sync translations
              uses: deriv-com/translations/.github/actions/extract_and_sync_translations@main
              with:
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                CROWDIN_BRANCH_NAME: ${{ secrets.sdfsdf }}
                CROWDIN_PROJECT_ID: ${{ secrets.sdfsf }}
                R2_ACCESS_KEY_ID:
